# Generated by Django 4.1.7 on 2023-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_description_recipe_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time",
            new_name="cooking_time",
        ),
    ]
